services:

  client:
    container_name: botaniq-client
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: client.dockerfile
    networks:
      - botaniq-network

  server:
    container_name: botaniq-server
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      - botaniq-network
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    container_name: botaniq-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    networks:
      - botaniq-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  botaniq-network:
    driver: bridge

volumes:
  traefik_letsencrypt:
  postgres_data:
