services:

  client:
    container_name: botaniq-client
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: client.dockerfile
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx.ssh.conf:/etc/nginx/conf.d/default.conf
    networks:
      - botaniq-network

  http-client:
    container_name: botaniq-client-http
    ports:
      - "80:80"
    profiles:
      - http
    build:
      context: .
      dockerfile: client.dockerfile
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - botaniq-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h;
      done"
    networks:
      - botaniq-network

  certbot-init:
    image: certbot/certbot
    profiles:
      - http
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  server:
    container_name: botaniq-server
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      - botaniq-network
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    container_name: botaniq-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    networks:
      - botaniq-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  botaniq-network:
    driver: bridge

volumes:
  traefik_letsencrypt:
  postgres_data:
